#!/bin/bash

# This is a sample DAEMON file which is started at boot time. 
# CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boot time!
#
# ATTENTION:
# Will be executed as user "root".

PLUGINNAME=REPLACELBPPLUGINDIR

# your code goes here

exit 0